### ISSUE TITLE
Rename references to "PIN" to "passphrase"

### ISSUE THREAD

**Issue by chrisccoulson** [canonical/secboot#113]
The PIN can be an arbitrary passphrase - nowhere is it enforced that it is actually a PIN. Whilst consumers of this package could enforce this, we don't and so references to "PIN" should just be renamed to "passphrase" everywhere it appears.

**Comment by pedronis** [comment]
Given that we need to abstract over things in one way or another in crypt.go. We can probably start there by renaming "PIN" to "UserPassphrase" in that context. Renaming PIN in the context of the TPM specific code is more involved, there's even a file called pin.go atm.

**Comment by chrisccoulson** [comment]
Closing this one now given that secboot is going to be treating PINs and passphrases as separate user authentication mechanisms, so both terms will exist but refer to different things. The repo today supports passphrases. https://github.com/canonical/secboot/pull/289 will introduce PINs, once it's rebased and has tests.
